/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const appContainer: string;

export {
	appContainer
};

declare const __default_export__: {
	appContainer: typeof appContainer;
};
export default __default_export__;
